spring.application.name=Employee-Management-BL

# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/EMPBL
spring.datasource.username=postgres
spring.datasource.password=5481
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT 
jwt.secret=IAmGonnaBecomeTheKingOfThePirates
jwt.expiration=86400000


#swagger config
# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# This disables the failing actuator scan
springdoc.show-actuator=false